schema_version: 20180708
name: doctor-create
version: 0.0.12
runtime: java
build_image: fnproject/fn-java-fdk-build:jdk11-1.0.86
run_image: fnproject/fn-java-fdk:jre11-1.0.86
cmd: DoctorFunction::create
triggers:
- name: doctor-create-trigger
  type: http
  source: /doctor-create-trigger
