schema_version: 20180708
name: flow
version: 0.0.5
runtime: java
build_image: fnproject/fn-java-fdk-build:jdk11-1.0.86
run_image: fnproject/fn-java-fdk:jre11-1.0.86
cmd: HelloFunction::handleRequest
triggers:
- name: flow
  type: http
  source: /flow
