schema_version: 20180708
name: create
version: 0.0.5
runtime: java
build_image: fnproject/fn-java-fdk-build:jdk11-1.0.86
run_image: fnproject/fn-java-fdk:jre11-1.0.86
cmd: com.cgm.patient.PatientFunction::create
triggers:
- name: create-trigger
  type: http
  source: /create-trigger
